### ISSUE TITLE
Storing alerts 

### ISSUE THREAD

**Issue by n3storm** [zix99/sshsysmon#1]
Hi zix99,
I'm loving sshsysmon.

Have you planned to store alerts to have some history?. Something light in sqlite will be enough.

I am planning myself to build a simple web dashboard and some history will be great. I may want to present it a la "status.io".

So it's two things:
  - dashboard overview 
  - status

Cheers and thanks for sharing

**Comment by zix99** [comment]
Hi n3storm,

I apologize, somehow I didn't notice this until today. Sqlite might be a good idea, but I'm wondering if it should be part of the core script or a plugin.

I recently added an output to create appended log files, but it sounds like you want all the metrics and not just alerts.

This is definitely something I want to implement, but id like to keep it as simple as possible.

Best,
Chris

**Comment by zix99** [comment]
There is a new channel that outputs alerts via a tabs-separated document, which you can prepend to a text file and parse later via `>>`.  Maybe more importantly, I refactored the channel/inspector/driver code to be loaded as plugins, rather than being imported, so you can write your own channel for sqlite if that works for you.

Please let me know if you don't think that that solution is sufficient, and I can reconsider.
